### ISSUE TITLE
code cell with syntax error gets erased on toggle

### ISSUE THREAD

**Issue by namin** [ekzhang/percival#11]
Steps to reproduce:
1. Create a code cell.
2. Write invalid code, such as: `1, 2, 3`. The code block is highlighted in orange.
3. Click the down arrow to toggle the visibility of the code block, rendering it not visible.
4. Click the right arrow to toggle visibility of the code block, rendering it visible.
5. The code block is empty, while expected to contain `1, 2, 3`.

**Comment by ekzhang** [comment]
Hi, I believe the confusion here is the orange color. Actually, the orange highlight is not a syntax error - it simply means that the code was changed and not yet saved / run. You need to run a code cell with Shift+Enter before it is saved. See the two images below, before and after pressing Shift+Enter.

![image](https://user-images.githubusercontent.com/7550632/148113197-92cede90-5b7b-4b23-a57a-8166ae8c8c63.png)

![image](https://user-images.githubusercontent.com/7550632/148113222-c3f90447-bdaf-49e4-94a6-89f8f0b4fbb0.png)

However, I agree that it is not desirable behavior for the editor's contents to be reset when the code visibility gets toggled.
